spring:
  application:
    name: savepay
#  security:
#    user:
#      name: binjumeoniz
#      password: 1234

  jpa:
    show-sql: true # sql ???? ??? ???? ??.
    properties:
      format_sql: true
      dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create

  datasource:
    url: jdbc:mysql://localhost:3306/savepay # mysql ?? ?? (?? ?? DB? ?? ? ??)
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password:


